// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EventTestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void eventTest() {
    driver.Navigate().GoToUrl("https://localhost:7265/");
    driver.FindElement(By.LinkText("Admin Panel")).Click();
    driver.FindElement(By.LinkText("Add new Event")).Click();
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("evetExample");
    driver.FindElement(By.Id("Description")).Click();
    driver.FindElement(By.Id("Description")).SendKeys("Hello example description");
    driver.FindElement(By.Id("ScheduledTime")).Click();
    driver.FindElement(By.Id("ScheduledTime")).SendKeys("2000-11-11T13:55");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
  }
}
