// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PasswordChangeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void passwordChange() {
    driver.Navigate().GoToUrl("https://localhost:7265/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.Id("navbarDropdown")).Click();
    driver.FindElement(By.LinkText("Manage")).Click();
    driver.FindElement(By.Id("change-password")).Click();
    driver.FindElement(By.Id("Input_OldPassword")).Click();
    driver.FindElement(By.Id("Input_OldPassword")).SendKeys("Ad123!");
    driver.FindElement(By.Id("Input_NewPassword")).Click();
    driver.FindElement(By.Id("Input_NewPassword")).SendKeys("Ad123!");
    driver.FindElement(By.Id("Input_ConfirmPassword")).Click();
    driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("Ad123!");
    driver.FindElement(By.CssSelector(".w-100")).Click();
  }
}
