// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DeleteWishlistTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void deleteWishlist() {
    driver.Navigate().GoToUrl("https://localhost:7265/");
    driver.Manage().Window.Size = new System.Drawing.Size(1565, 727);
    driver.FindElement(By.LinkText("Wishlist")).Click();
    driver.FindElement(By.LinkText("Store")).Click();
    driver.FindElement(By.Id("navbarDropdown")).Click();
    driver.FindElement(By.LinkText("Admin Panel")).Click();
    driver.FindElement(By.LinkText("Add new Game")).Click();
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Dark Siders");
    driver.FindElement(By.Id("ReleaseDate")).Click();
    driver.FindElement(By.Id("ReleaseDate")).SendKeys("1991-11-11T23:11");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.LinkText("Store")).Click();
    driver.FindElement(By.LinkText("Details")).Click();
    driver.FindElement(By.LinkText("Add to Wishlist")).Click();
    driver.FindElement(By.LinkText("Wishlist")).Click();
    driver.FindElement(By.LinkText("Wishlist")).Click();
    driver.FindElement(By.LinkText("Wishlist")).Click();
    driver.FindElement(By.LinkText("Delete")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
