// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LogintestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/Cdriver/");
        js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void logintest() {
        driver.Navigate().GoToUrl("https://localhost:7265/");
  
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(2000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("kh");
        Thread.Sleep(2000);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Admin!23");
        Thread.Sleep(2000);
        driver.FindElement(By.Id("login-submit")).Click();

  }
}
