// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegisterAccountTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registerAccount() {
    driver.Navigate().GoToUrl("https://localhost:7265/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.Id("register")).Click();
    driver.FindElement(By.Id("Input_FirstName")).Click();
    driver.FindElement(By.Id("Input_FirstName")).SendKeys("asd");
    driver.FindElement(By.Id("Input_LastName")).Click();
    driver.FindElement(By.Id("Input_LastName")).SendKeys("asd");
    driver.FindElement(By.Id("Input_Gender")).Click();
    driver.FindElement(By.Id("Input_Gender")).SendKeys("asd");
    driver.FindElement(By.Id("Input_DateOfBirth")).Click();
    driver.FindElement(By.Id("Input_DateOfBirth")).SendKeys("1991-11-11T23:11");
    driver.FindElement(By.Id("adv-ws-step1-btn-next")).Click();
    driver.FindElement(By.Id("Input_MailingAddress")).Click();
    driver.FindElement(By.Id("Input_MailingAddress")).SendKeys("asd");
    driver.FindElement(By.Id("Input_ShippingAddress")).Click();
    driver.FindElement(By.Id("Input_ShippingAddress")).SendKeys("asd");
    driver.FindElement(By.Id("adv-ws-step2-btn-next")).Click();
    driver.FindElement(By.Id("Input_Email")).Click();
    driver.FindElement(By.Id("Input_Username")).Click();
    driver.FindElement(By.Id("Input_Username")).SendKeys("e");
    driver.FindElement(By.Id("Input_Email")).Click();
    driver.FindElement(By.Id("Input_Email")).SendKeys("e@e.com");
    driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
    driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("Ad123!");
    driver.FindElement(By.Id("registerSubmit")).Click();
    driver.FindElement(By.Id("confirm-link")).Click();
    driver.Close();
  }
}
