// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.VisualBasic;

[TestFixture]
public class CVGS_Users_TEST
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver(@"C:/Cdriver/");
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();


    }



    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }


    /*
    [Test]
    public void RegisterNewAccount()
    {
        driver.Navigate().GoToUrl("https://localhost:7265/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.Id("register")).Click();

        Thread.Sleep(1000);

        driver.FindElement(By.Id("Input_FirstName")).Click();
        driver.FindElement(By.Id("Input_FirstName")).SendKeys("asd");
        driver.FindElement(By.Id("Input_LastName")).Click();
        driver.FindElement(By.Id("Input_LastName")).SendKeys("asd");
        driver.FindElement(By.Id("Input_Gender")).Click();
        driver.FindElement(By.Id("Input_Gender")).SendKeys("asd");
       // driver.FindElement(By.Id("Input_DateOfBirth")).Click();
       
        driver.FindElement(By.Id("Input_DateOfBirth")).SendKeys("2012-05-12T12:00");
        Thread.Sleep(2000);
        driver.FindElement(By.Id("adv-ws-step1-btn-next")).Click();
        driver.FindElement(By.Id("Input_MailingAddress")).Click();
        driver.FindElement(By.Id("Input_MailingAddress")).SendKeys("asd");
        driver.FindElement(By.Id("Input_ShippingAddress")).Click();
        driver.FindElement(By.Id("Input_ShippingAddress")).SendKeys("asd");
        driver.FindElement(By.Id("adv-ws-step2-btn-next")).Click();

        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("q");
        driver.FindElement(By.Id("Input_Email")).Click();
        driver.FindElement(By.Id("Input_Email")).SendKeys("e@e.com");
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("Ad123!");
        driver.FindElement(By.Id("registerSubmit")).Click();

        Thread.Sleep(2000);
        driver.FindElement(By.Id("confirm-link")).Click();
        driver.Close();

    }
    */
    


    [Test]
    public void DeleteWishList()
    {
        driver.Navigate().GoToUrl("https://localhost:7265/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("c");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();



        driver.FindElement(By.LinkText("Wishlist")).Click();
        driver.FindElement(By.LinkText("Delete")).Click();
        driver.FindElement(By.CssSelector(".btn-danger")).Click();



    }



    [Test]
    public void Recieve_promotion()
    {
        driver.Navigate().GoToUrl("https://localhost:7265/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("c");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();


        driver.FindElement(By.Id("navbarDropdown")).Click();
        driver.FindElement(By.LinkText("Manage")).Click();
        driver.FindElement(By.Id("Input_ReceivePromotion")).Click();
        driver.FindElement(By.Id("update-profile-button")).Click();
        driver.Close();



    }


    [Test]
    public void Shiping_Mailing_AddressChange()
    {
        driver.Navigate().GoToUrl("https://localhost:7265/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("c");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();


   
        driver.FindElement(By.Id("navbarDropdown")).Click();
        driver.FindElement(By.LinkText("Manage")).Click();


        driver.FindElement(By.Id("Input_MailingAddress")).Click();
        driver.FindElement(By.CssSelector(".row:nth-child(3)")).Click();
        driver.FindElement(By.Id("Input_MailingAddress")).SendKeys("ASDASDnew");
        driver.FindElement(By.Id("Input_ShippingAddress")).SendKeys("ASDASDNEW");
        driver.FindElement(By.Id("update-profile-button")).Click();
   


    }







    [Test]
    public void AddFriends()
    {

        driver.Navigate().GoToUrl("https://localhost:7265/");

        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("c");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();



        driver.FindElement(By.Id("navbarCommunityDropdown")).Click();
        driver.FindElement(By.LinkText("Friends")).Click();
        driver.FindElement(By.LinkText("Add Friend")).Click();
        driver.FindElement(By.CssSelector(".control-label")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("k");
        driver.FindElement(By.CssSelector(".btn-primary")).Click();
        driver.FindElement(By.LinkText("Add Friend")).Click();
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("e");
        driver.FindElement(By.CssSelector(".btn-primary")).Click();
        driver.FindElement(By.LinkText("Add Friend")).Click();
        driver.FindElement(By.Id("Username")).Click();
        driver.FindElement(By.Id("Username")).SendKeys("c");
        driver.FindElement(By.CssSelector(".btn-primary")).Click();
        driver.Close();
    }


    [Test]
    public void AddWishListTest()
    {
        driver.Navigate().GoToUrl("https://localhost:7265/");

        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("k");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();




        driver.FindElement(By.LinkText("Store")).Click();
        driver.FindElement(By.LinkText("Details")).Click();
        driver.FindElement(By.LinkText("Add to Wishlist")).Click();
        driver.FindElement(By.LinkText("Store")).Click();
        driver.FindElement(By.LinkText("Details")).Click();
        driver.FindElement(By.LinkText("Add to Wishlist")).Click();
        driver.FindElement(By.LinkText("Store")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.LinkText("Wishlist")).Click();
        Thread.Sleep(2000);

    }





    [Test]
    public void CheckFriends()
    {

        driver.Navigate().GoToUrl("https://localhost:7265/");

        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("e");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();


        driver.FindElement(By.Id("navbarCommunityDropdown")).Click();
        driver.FindElement(By.LinkText("Friends")).Click();
        Thread.Sleep(2000);

        driver.Close();
    }




    [Test]
    public void CheckFriendsWishList()
    {

        driver.Navigate().GoToUrl("https://localhost:7265/");

        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("c");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();



        driver.FindElement(By.Id("navbarCommunityDropdown")).Click();
        driver.FindElement(By.LinkText("Friends")).Click();
        Thread.Sleep(2000);
        driver.FindElement(By.LinkText("View Wishlist")).Click();
        Thread.Sleep(1000);
        driver.Navigate().Back();
      
        try
        {

            for(int i = 2; i < 100; i++)
            {
                         
                driver.FindElement(By.CssSelector("tr:nth-child(" + i.ToString() + ") a:nth-child(2)")).Click();
                Thread.Sleep(1000);
                driver.Navigate().Back();
              

            }

        }
        catch(Exception e)
        {

        }
   
        driver.Close();
    }





    [Test]
    public void RegisterForEvent()
    {

        driver.Navigate().GoToUrl("https://localhost:7265/");

        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("login")).Click();
        Thread.Sleep(500);
        driver.FindElement(By.Id("Input_Username")).Click();
        driver.FindElement(By.Id("Input_Username")).SendKeys("k");
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).Click();
        Thread.Sleep(100);
        driver.FindElement(By.Id("Input_Password")).SendKeys("Ad123!");
        Thread.Sleep(100);
        driver.FindElement(By.Id("login-submit")).Click();



        driver.FindElement(By.Id("navbarCommunityDropdown")).Click();
        driver.FindElement(By.LinkText("Events")).Click();
        driver.FindElement(By.LinkText("Register")).Click();

        driver.Close();
    }



}